// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Sheep.Site.Api.Data;
using System;

namespace Sheep.Site.Api.Migrations
{
    [DbContext(typeof(SheepSiteContext))]
    [Migration("20180409202731_initi")]
    partial class initi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Sheep.Site.Api.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("sheepDOB");

                    b.Property<char>("sheepGender");

                    b.HasKey("Id");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Sheep.Site.Api.Models.Pregnancy", b =>
                {
                    b.Property<int>("pregnancyID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AnimalId");

                    b.Property<string>("actBirth");

                    b.Property<string>("conceptionDate");

                    b.Property<string>("estBirth");

                    b.Property<int>("numberOfBabies");

                    b.Property<string>("pregnancyComment");

                    b.HasKey("pregnancyID");

                    b.HasIndex("AnimalId");

                    b.ToTable("Pregnancies");
                });

            modelBuilder.Entity("Sheep.Site.Api.Models.Treatment", b =>
                {
                    b.Property<int>("treatmentID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AnimalId");

                    b.Property<string>("treatmentComment");

                    b.Property<DateTime>("treatmentDate");

                    b.Property<string>("treatmentDosage");

                    b.Property<string>("treatmentName");

                    b.HasKey("treatmentID");

                    b.HasIndex("AnimalId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("Sheep.Site.Api.Models.Vaccine", b =>
                {
                    b.Property<int>("vaccineID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AnimalId");

                    b.Property<string>("vaccineComment");

                    b.Property<DateTime>("vaccineDate");

                    b.Property<string>("vaccineDosage");

                    b.Property<string>("vaccineName");

                    b.HasKey("vaccineID");

                    b.HasIndex("AnimalId");

                    b.ToTable("Vaccines");
                });

            modelBuilder.Entity("Sheep.Site.Api.Models.Pregnancy", b =>
                {
                    b.HasOne("Sheep.Site.Api.Models.Animal", "Animal")
                        .WithMany("pregnancyNames")
                        .HasForeignKey("AnimalId");
                });

            modelBuilder.Entity("Sheep.Site.Api.Models.Treatment", b =>
                {
                    b.HasOne("Sheep.Site.Api.Models.Animal", "Animal")
                        .WithMany("treatmentNames")
                        .HasForeignKey("AnimalId");
                });

            modelBuilder.Entity("Sheep.Site.Api.Models.Vaccine", b =>
                {
                    b.HasOne("Sheep.Site.Api.Models.Animal", "Animal")
                        .WithMany("vaccineNames")
                        .HasForeignKey("AnimalId");
                });
#pragma warning restore 612, 618
        }
    }
}
